steps:
- name: 'python:3.8'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      pip install google-cloud-storage
      pip install google-cloud-pubsub
      python scripts/process_file.py --bucket $_BUCKET_NAME --object $_OBJECT_NAME

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _BUCKET_NAME: ''
  _OBJECT_NAME: ''
